### ISSUE TITLE
DataInputStream::read_until_async asserts when empty

### ISSUE THREAD

**Issue by heftig** [gtk-rs/gio#276]
This code (using `gio = "0.8.0, glib = "0.9.1"`) reads a line from stdin asynchronously, echos it back out, then exits:

```rust
use gio::prelude::*;

fn main() {
    let mainloop = glib::MainLoop::new(None, true);
    let input = unsafe {
        struct RawFdWrap(i32);

        impl std::os::unix::io::IntoRawFd for RawFdWrap {
            fn into_raw_fd(self) -> std::os::unix::io::RawFd {
                self.0 as _
            }
        }

        gio::UnixInputStream::new(RawFdWrap(0))
    };

    let input = gio::DataInputStream::new(&input);

    {
        let mainloop = mainloop.clone();
        input.read_until_async(
            "\n",
            glib::PRIORITY_DEFAULT,
            gio::NONE_CANCELLABLE,
            move |res| {
                println!("{}", res.unwrap().0);
                mainloop.quit();
            },
        );
    }

    mainloop.run();
}
```

But it asserts when it reads an empty line or an immediate EOF:
```
thread 'main' panicked at 'assertion failed: !ptr.is_null()', /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.9.1/src/gstring.rs:35:9
stack backtrace:
   0:     0x55784c7381a4 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55784c7381a4 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55784c7381a4 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55784c7381a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55784c7509ac - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55784c736a47 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55784c73a4be - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55784c73a4be - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55784c73a4be - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x55784c73a1b1 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x55784c73ab0b - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55784c732423 - std::panicking::begin_panic::ha904792d2b03cbc9
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:400
  12:     0x55784c73065f - glib::gstring::GString::new::ha51bbcc739583cae
                               at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.9.1/src/gstring.rs:35
  13:     0x55784c7306fc - <glib::gstring::GString as glib::translate::FromGlibPtrFull<*mut i8>>::from_glib_full::hdcd48933a5a36413
                               at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.9.1/src/gstring.rs:290
  14:     0x55784c72fbbb - glib::translate::from_glib_full::hde6253237b3c3fcc
                               at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.9.1/src/translate.rs:1221
  15:     0x55784c72d8f2 - <O as gio::auto::data_input_stream::DataInputStreamExt>::read_until_async::read_until_async_trampoline::hbcc619cc827bbcc9
                               at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.8.0/src/auto/data_input_stream.rs:419
  16:     0x7f3260d8cdc4 - <unknown>
  17:     0x7f3260d927a7 - <unknown>
  18:     0x7f3260dec45a - <unknown>
  19:     0x7f3260dec886 - <unknown>
  20:     0x7f3260df8294 - <unknown>
  21:     0x7f3260d8cdc4 - <unknown>
  22:     0x7f3260d927a7 - <unknown>
  23:     0x7f3260df81b9 - <unknown>
  24:     0x7f3260dc5e8c - <unknown>
  25:     0x7f3260d8cdc4 - <unknown>
  26:     0x7f3260d927a7 - <unknown>
  27:     0x7f3260dc9714 - <unknown>
  28:     0x7f3260dc9799 - <unknown>
  29:     0x7f3260bbc26f - g_main_context_dispatch
  30:     0x7f3260bbe1b1 - <unknown>
  31:     0x7f3260bbf0c3 - g_main_loop_run
  32:     0x55784c7310c7 - glib::auto::main_loop::MainLoop::run::h59f69fb08fb751ba
                               at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.9.1/src/auto/main_loop.rs:46
  33:     0x55784c72ed08 - foo::main::hd596e2be2ba6dd19
                               at src/main.rs:32
  34:     0x55784c72d3f0 - std::rt::lang_start::{{closure}}::h29118bb61f6df9dc
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  35:     0x55784c73a583 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  36:     0x55784c73a583 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  37:     0x55784c73bd5a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  38:     0x55784c73afed - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  39:     0x55784c73afed - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  40:     0x55784c73afed - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  41:     0x55784c72d3c9 - std::rt::lang_start::ha96fda9eb67ca34b
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  42:     0x55784c72edaa - main
  43:     0x7f326096f153 - __libc_start_main
  44:     0x55784c72d16e - _start
  45:                0x0 - <unknown>
```

**Comment by GuillaumeGomez** [comment]
cc @sdroege

**Comment by sdroege** [comment]
Yeah, all these need to use an `Option<GString>` instead, i.e. making the parameter nullable. Should be doable via the `Gir.toml`.

Do you want to provide a PR for that? Affects all the `read_until()` and `read_upto()` functions.

**Comment by sdroege** [comment]
@heftig ?

**Comment by heftig** [comment]
Sorry, I just saw this playing around with gio-rs. I'm busy with more important stuff ATM.

**Comment by sdroege** [comment]
Fixing that then, thanks

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gio/pull/281
